# Generated by Django 3.1.1 on 2020-09-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
